# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, workflow_dispatch ]

jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          java: [ 11, 17, 21 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.os }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install jaxb plugin
      run: cd .. && git clone https://github.com/mojohaus/jaxb2-maven-plugin.git && cd jaxb2-maven-plugin/ && git checkout jaxb2-maven-plugin-3.0.0 && mvn clean install -DskipTests
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml 
    - name: Publish Test Report ${{ matrix.java }} OS ${{ matrix.os }}
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         check_name: Test Report ${{ matrix.java }} OS ${{ matrix.os }}
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Results (Java ${{ matrix.java }} OS ${{ matrix.os }})
        path: |
          kopeme-core/target/surefire-reports/*
          kopeme-junit/target/surefire-reports/*
          kopeme-junit3/target/surefire-reports/*
